<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Regressions | ESS 580 - Intro to Data Science, Final Project</title>
  <meta name="description" content="This is a simple bookdown created to present the first six data science assignments of ESS 580, Spring 2022." />
  <meta name="generator" content="bookdown 0.25 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Regressions | ESS 580 - Intro to Data Science, Final Project" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a simple bookdown created to present the first six data science assignments of ESS 580, Spring 2022." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Regressions | ESS 580 - Intro to Data Science, Final Project" />
  
  <meta name="twitter:description" content="This is a simple bookdown created to present the first six data science assignments of ESS 580, Spring 2022." />
  

<meta name="author" content="Daniel Cleveland" />


<meta name="date" content="2022-04-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="lake-water-quality-analysis.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/dygraphs-1.1.1/shapes.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.6/dygraphs.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.1.1/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.1.1/leaflet-providers-plugin.js"></script>
<link href="libs/HomeButton-0.0.1/home-button.css" rel="stylesheet" />
<script src="libs/HomeButton-0.0.1/home-button.js"></script>
<script src="libs/HomeButton-0.0.1/easy-button-src.min.js"></script>
<script src="libs/clipboard-0.0.1/setClipboardText.js"></script>
<link href="libs/mapviewCSS-0.0.1/mapview-popup.css" rel="stylesheet" />
<link href="libs/mapviewCSS-0.0.1/mapview.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction<span></span></a></li>
<li class="chapter" data-level="2" data-path="poudre-river-rmarkdown-and-github-familiarization.html"><a href="poudre-river-rmarkdown-and-github-familiarization.html"><i class="fa fa-check"></i><b>2</b> Poudre River: RMarkdown and GitHub Familiarization<span></span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="poudre-river-rmarkdown-and-github-familiarization.html"><a href="poudre-river-rmarkdown-and-github-familiarization.html#methods"><i class="fa fa-check"></i><b>2.1</b> Methods<span></span></a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="poudre-river-rmarkdown-and-github-familiarization.html"><a href="poudre-river-rmarkdown-and-github-familiarization.html#sitedescription"><i class="fa fa-check"></i><b>2.1.1</b> SiteDescription<span></span></a></li>
<li class="chapter" data-level="2.1.2" data-path="poudre-river-rmarkdown-and-github-familiarization.html"><a href="poudre-river-rmarkdown-and-github-familiarization.html#data-acquisition-and-plotting-tests"><i class="fa fa-check"></i><b>2.1.2</b> Data Acquisition and Plotting tests<span></span></a></li>
<li class="chapter" data-level="2.1.3" data-path="poudre-river-rmarkdown-and-github-familiarization.html"><a href="poudre-river-rmarkdown-and-github-familiarization.html#data-download"><i class="fa fa-check"></i><b>2.1.3</b> Data Download<span></span></a></li>
<li class="chapter" data-level="2.1.4" data-path="poudre-river-rmarkdown-and-github-familiarization.html"><a href="poudre-river-rmarkdown-and-github-familiarization.html#static-data-plotter"><i class="fa fa-check"></i><b>2.1.4</b> Static Data Plotter<span></span></a></li>
<li class="chapter" data-level="2.1.5" data-path="poudre-river-rmarkdown-and-github-familiarization.html"><a href="poudre-river-rmarkdown-and-github-familiarization.html#interactive-data-plotter-creating-interactive-plots"><i class="fa fa-check"></i><b>2.1.5</b> Interactive Data Plotter *(Creating Interactive Plots)<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="poudre-river-rmarkdown-and-github-familiarization.html"><a href="poudre-river-rmarkdown-and-github-familiarization.html#results"><i class="fa fa-check"></i><b>2.2</b> Results<span></span></a></li>
<li class="chapter" data-level="2.3" data-path="poudre-river-rmarkdown-and-github-familiarization.html"><a href="poudre-river-rmarkdown-and-github-familiarization.html#assignment"><i class="fa fa-check"></i><b>2.3</b> Assignment<span></span></a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="poudre-river-rmarkdown-and-github-familiarization.html"><a href="poudre-river-rmarkdown-and-github-familiarization.html#dygraph-example."><i class="fa fa-check"></i><b>2.3.1</b> DyGraph example.<span></span></a></li>
<li class="chapter" data-level="2.3.2" data-path="poudre-river-rmarkdown-and-github-familiarization.html"><a href="poudre-river-rmarkdown-and-github-familiarization.html#poudre-paragraph"><i class="fa fa-check"></i><b>2.3.2</b> Poudre Paragraph<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="hayman-fire-recovery.html"><a href="hayman-fire-recovery.html"><i class="fa fa-check"></i><b>3</b> Hayman Fire Recovery<span></span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="hayman-fire-recovery.html"><a href="hayman-fire-recovery.html#reading-in-and-preparing-fire-data"><i class="fa fa-check"></i><b>3.1</b> Reading In and Preparing Fire Data<span></span></a></li>
<li class="chapter" data-level="3.2" data-path="hayman-fire-recovery.html"><a href="hayman-fire-recovery.html#the-assignment"><i class="fa fa-check"></i><b>3.2</b> The Assignment<span></span></a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="hayman-fire-recovery.html"><a href="hayman-fire-recovery.html#question-1"><i class="fa fa-check"></i><b>3.2.1</b> Question 1)<span></span></a></li>
<li class="chapter" data-level="3.2.2" data-path="hayman-fire-recovery.html"><a href="hayman-fire-recovery.html#question-2"><i class="fa fa-check"></i><b>3.2.2</b> Question 2<span></span></a></li>
<li class="chapter" data-level="3.2.3" data-path="hayman-fire-recovery.html"><a href="hayman-fire-recovery.html#q3"><i class="fa fa-check"></i><b>3.2.3</b> Q3<span></span></a></li>
<li class="chapter" data-level="3.2.4" data-path="hayman-fire-recovery.html"><a href="hayman-fire-recovery.html#question-4"><i class="fa fa-check"></i><b>3.2.4</b> Question 4<span></span></a></li>
<li class="chapter" data-level="3.2.5" data-path="hayman-fire-recovery.html"><a href="hayman-fire-recovery.html#question-5"><i class="fa fa-check"></i><b>3.2.5</b> Question 5)<span></span></a></li>
<li class="chapter" data-level="3.2.6" data-path="hayman-fire-recovery.html"><a href="hayman-fire-recovery.html#bonus-question-1-redo-all-problems-with-spread-and-gather-using-modern-tidyverse-syntax."><i class="fa fa-check"></i><b>3.2.6</b> Bonus Question 1: Redo all problems with <code>spread</code> and <code>gather</code> using modern tidyverse syntax.<span></span></a></li>
<li class="chapter" data-level="3.2.7" data-path="hayman-fire-recovery.html"><a href="hayman-fire-recovery.html#bonus-question-2-use-climage-engine-to-pull-the-same-data-for-the-assignment-but-updated-with-20202021-data."><i class="fa fa-check"></i><b>3.2.7</b> Bonus Question 2: Use Climage Engine to pull the same data for the assignment, but updated with 2020/2021 data.<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="snow-data.html"><a href="snow-data.html"><i class="fa fa-check"></i><b>4</b> Snow Data<span></span></a>
<ul>
<li class="chapter" data-level="4.1" data-path="snow-data.html"><a href="snow-data.html#simple-web-scraping"><i class="fa fa-check"></i><b>4.1</b> Simple web scraping<span></span></a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="snow-data.html"><a href="snow-data.html#reading-an-html"><i class="fa fa-check"></i><b>4.1.1</b> Reading an html<span></span></a></li>
<li class="chapter" data-level="4.1.2" data-path="snow-data.html"><a href="snow-data.html#data-download-1"><i class="fa fa-check"></i><b>4.1.2</b> Data Download<span></span></a></li>
<li class="chapter" data-level="4.1.3" data-path="snow-data.html"><a href="snow-data.html#data-read-in"><i class="fa fa-check"></i><b>4.1.3</b> Data read-in<span></span></a></li>
<li class="chapter" data-level="4.1.4" data-path="snow-data.html"><a href="snow-data.html#plot-snow-data"><i class="fa fa-check"></i><b>4.1.4</b> Plot snow data<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="snow-data.html"><a href="snow-data.html#assignment-1"><i class="fa fa-check"></i><b>4.2</b> Assignment:<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="lagos-data-analysis.html"><a href="lagos-data-analysis.html"><i class="fa fa-check"></i><b>5</b> LAGOS Data Analysis<span></span></a>
<ul>
<li class="chapter" data-level="5.1" data-path="lagos-data-analysis.html"><a href="lagos-data-analysis.html#setting-up-for-the-assignment"><i class="fa fa-check"></i><b>5.1</b> Setting Up for the Assignment<span></span></a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="lagos-data-analysis.html"><a href="lagos-data-analysis.html#loading-in-data"><i class="fa fa-check"></i><b>5.1.1</b> Loading in data<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="lagos-data-analysis.html"><a href="lagos-data-analysis.html#assignment-2"><i class="fa fa-check"></i><b>5.2</b> Assignment<span></span></a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="lagos-data-analysis.html"><a href="lagos-data-analysis.html#show-a-map-outline-of-iowa-and-illinois-similar-to-minnesota-map-upstream"><i class="fa fa-check"></i><b>5.2.1</b> 1) Show a map outline of Iowa and Illinois (similar to Minnesota map upstream)<span></span></a></li>
<li class="chapter" data-level="5.2.2" data-path="lagos-data-analysis.html"><a href="lagos-data-analysis.html#subset-lagos-data-to-these-sites-how-many-sites-are-in-illinois-and-iowa-combined-how-does-this-compare-to-minnesota"><i class="fa fa-check"></i><b>5.2.2</b> 2) Subset LAGOS data to these sites, how many sites are in Illinois and Iowa combined? How does this compare to Minnesota?<span></span></a></li>
<li class="chapter" data-level="5.2.3" data-path="lagos-data-analysis.html"><a href="lagos-data-analysis.html#what-is-the-distribution-of-lake-size-in-iowa-vs.-minnesota"><i class="fa fa-check"></i><b>5.2.3</b> 3) What is the distribution of lake size in Iowa vs. Minnesota?<span></span></a></li>
<li class="chapter" data-level="5.2.4" data-path="lagos-data-analysis.html"><a href="lagos-data-analysis.html#make-an-interactive-plot-of-lakes-in-iowa-and-illinois-and-color-them-by-lake-area-in-hectares"><i class="fa fa-check"></i><b>5.2.4</b> 4) Make an interactive plot of lakes in Iowa and Illinois and color them by lake area in hectares<span></span></a></li>
<li class="chapter" data-level="5.2.5" data-path="lagos-data-analysis.html"><a href="lagos-data-analysis.html#what-other-data-sources-might-we-use-to-understand-how-reservoirs-and-natural-lakes-vary-in-size-in-these-three-states"><i class="fa fa-check"></i><b>5.2.5</b> 5) What other data sources might we use to understand how reservoirs and natural lakes vary in size in these three states?<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="lake-water-quality-analysis.html"><a href="lake-water-quality-analysis.html"><i class="fa fa-check"></i><b>6</b> Lake Water Quality Analysis<span></span></a>
<ul>
<li class="chapter" data-level="6.1" data-path="lake-water-quality-analysis.html"><a href="lake-water-quality-analysis.html#preparing-for-lagos-analysis-assignment"><i class="fa fa-check"></i><b>6.1</b> Preparing for LAGOS Analysis Assignment<span></span></a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="lake-water-quality-analysis.html"><a href="lake-water-quality-analysis.html#loading-in-data-1"><i class="fa fa-check"></i><b>6.1.1</b> Loading in data<span></span></a></li>
<li class="chapter" data-level="6.1.2" data-path="lake-water-quality-analysis.html"><a href="lake-water-quality-analysis.html#creating-map-of-mean-chl_a"><i class="fa fa-check"></i><b>6.1.2</b> Creating Map of Mean Chl_a<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="lake-water-quality-analysis.html"><a href="lake-water-quality-analysis.html#class-work"><i class="fa fa-check"></i><b>6.2</b> Class work<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regressions.html"><a href="regressions.html"><i class="fa fa-check"></i><b>7</b> Regressions<span></span></a>
<ul>
<li class="chapter" data-level="7.1" data-path="regressions.html"><a href="regressions.html#weather-data-analysis"><i class="fa fa-check"></i><b>7.1</b> Weather Data Analysis<span></span></a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="regressions.html"><a href="regressions.html#load-the-prism-daily-maximum-temperature"><i class="fa fa-check"></i><b>7.1.1</b> Load the PRISM daily maximum temperature<span></span></a></li>
<li class="chapter" data-level="7.1.2" data-path="regressions.html"><a href="regressions.html#temperature-trends"><i class="fa fa-check"></i><b>7.1.2</b> Temperature Trends<span></span></a></li>
<li class="chapter" data-level="7.1.3" data-path="regressions.html"><a href="regressions.html#multiple-regression-quadratic-time-trend"><i class="fa fa-check"></i><b>7.1.3</b> Multiple Regression – Quadratic Time Trend<span></span></a></li>
<li class="chapter" data-level="7.1.4" data-path="regressions.html"><a href="regressions.html#download-nass-corn-yield-data"><i class="fa fa-check"></i><b>7.1.4</b> Download NASS corn yield data<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="regressions.html"><a href="regressions.html#assignment-3"><i class="fa fa-check"></i><b>7.2</b> Assignment<span></span></a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="regressions.html"><a href="regressions.html#question-1a-extract-winneshiek-county-corn-yields-fit-a-linear-time-trend-make-a-plot.-is-there-a-significant-time-trend"><i class="fa fa-check"></i><b>7.2.1</b> Question 1a: Extract Winneshiek County corn yields, fit a linear time trend, make a plot. Is there a significant time trend?<span></span></a></li>
<li class="chapter" data-level="7.2.2" data-path="regressions.html"><a href="regressions.html#question-1b-fit-a-quadratic-time-trend-i.e.-year-year2-and-make-a-plot.-is-there-evidence-for-slowing-yield-growth"><i class="fa fa-check"></i><b>7.2.2</b> Question 1b: Fit a quadratic time trend (i.e., year + year^2) and make a plot. Is there evidence for slowing yield growth?<span></span></a></li>
<li class="chapter" data-level="7.2.3" data-path="regressions.html"><a href="regressions.html#question-2-time-series-lets-analyze-the-relationship-between-temperature-and-yields-for-the-winneshiek-county-time-series.-use-data-on-yield-and-summer-avg-tmax.-is-adding-year-or-tmax2-to-your-model-helpful-make-a-plot-and-interpret-the-results."><i class="fa fa-check"></i><b>7.2.3</b> Question 2 – Time Series: Let’s analyze the relationship between temperature and yields for the Winneshiek County time series. Use data on yield and summer avg Tmax. Is adding year or Tmax^2 to your model helpful? Make a plot and interpret the results.<span></span></a></li>
<li class="chapter" data-level="7.2.4" data-path="regressions.html"><a href="regressions.html#question-3-cross-section-analyze-the-relationship-between-temperature-and-yield-across-all-counties-in-2018.-is-there-a-relationship-interpret-the-results."><i class="fa fa-check"></i><b>7.2.4</b> Question 3 – Cross-Section: Analyze the relationship between temperature and yield across all counties in 2018. Is there a relationship? Interpret the results.<span></span></a></li>
<li class="chapter" data-level="7.2.5" data-path="regressions.html"><a href="regressions.html#question-4-panel"><i class="fa fa-check"></i><b>7.2.5</b> Question 4 – Panel:<span></span></a></li>
<li class="chapter" data-level="7.2.6" data-path="regressions.html"><a href="regressions.html#question-5-soybeans-download-nass-data-on-soybean-yields-and-explore-either-a-time-series-relationship-for-a-given-county-the-cross-sectional-relationship-for-a-given-year-or-a-panel-across-all-counties-and-years."><i class="fa fa-check"></i><b>7.2.6</b> Question 5 – Soybeans: Download NASS data on soybean yields and explore either a time series relationship for a given county, the cross-sectional relationship for a given year, or a panel across all counties and years.<span></span></a></li>
<li class="chapter" data-level="7.2.7" data-path="regressions.html"><a href="regressions.html#bonus-1-find-a-package-to-make-a-county-map-of-iowa-displaying-some-sort-of-information-about-yields-or-weather.-interpret-your-map."><i class="fa fa-check"></i><b>7.2.7</b> Bonus #1: Find a package to make a county map of Iowa displaying some sort of information about yields or weather. Interpret your map.<span></span></a></li>
<li class="chapter" data-level="7.2.8" data-path="regressions.html"><a href="regressions.html#bonus-2-challenge-question---map-trends-in-corn-yields-by-county-across-iowa.-interpret-your-map."><i class="fa fa-check"></i><b>7.2.8</b> Bonus #2: Challenge question - map trends in corn yields by county across Iowa. Interpret your map.<span></span></a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ESS 580 - Intro to Data Science, Final Project</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regressions" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Regressions<a href="regressions.html#regressions" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Assignment 6: Using PRISM weather data and USDA NASS crop data to learn multiple regression</p>
<div id="weather-data-analysis" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Weather Data Analysis<a href="regressions.html#weather-data-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="load-the-prism-daily-maximum-temperature" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Load the PRISM daily maximum temperature<a href="regressions.html#load-the-prism-daily-maximum-temperature" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="regressions.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># daily max temperature</span></span>
<span id="cb68-2"><a href="regressions.html#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="co"># dimensions of the data:  counties x days x years</span></span>
<span id="cb68-3"><a href="regressions.html#cb68-3" aria-hidden="true" tabindex="-1"></a>prism <span class="ot">&lt;-</span> <span class="fu">readMat</span>(<span class="st">&quot;data_reg/prismiowa.mat&quot;</span>)</span>
<span id="cb68-4"><a href="regressions.html#cb68-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-5"><a href="regressions.html#cb68-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-6"><a href="regressions.html#cb68-6" aria-hidden="true" tabindex="-1"></a><span class="co">#look at all temp for county #1 in first year of data (1981):</span></span>
<span id="cb68-7"><a href="regressions.html#cb68-7" aria-hidden="true" tabindex="-1"></a>t_1981_c1 <span class="ot">&lt;-</span> prism<span class="sc">$</span>tmaxdaily.iowa[<span class="dv">1</span>,,<span class="dv">1</span>]</span>
<span id="cb68-8"><a href="regressions.html#cb68-8" aria-hidden="true" tabindex="-1"></a>t_1981_c1[<span class="dv">366</span>]  <span class="co">#(shows that 1981 was not a leap year.)</span></span></code></pre></div>
<pre><code>## [1] NaN</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="regressions.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">366</span>, t_1981_c1, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/14%20tmax%20data-1.png" width="672" /></p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="regressions.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb71-2"><a href="regressions.html#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">366</span>, <span class="at">y=</span>t_1981_c1))<span class="sc">+</span></span>
<span id="cb71-3"><a href="regressions.html#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb71-4"><a href="regressions.html#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;day of year&quot;</span>) <span class="sc">+</span></span>
<span id="cb71-5"><a href="regressions.html#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;daily maximum temperature (°C)&quot;</span>)<span class="sc">+</span>  <span class="co">#use Alt+0176 as keyboard shortcut to get the degree symbol!!!</span></span>
<span id="cb71-6"><a href="regressions.html#cb71-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Daily Maximum Temperature for County #1 in Iowa&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/14%20tmax%20data-2.png" width="672" /></p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="regressions.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># assign dimension names to tmax matrix</span></span>
<span id="cb72-2"><a href="regressions.html#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(prism<span class="sc">$</span>tmaxdaily.iowa) <span class="ot">&lt;-</span> <span class="fu">list</span>(prism<span class="sc">$</span>COUNTYFP, </span>
<span id="cb72-3"><a href="regressions.html#cb72-3" aria-hidden="true" tabindex="-1"></a>                                       <span class="dv">1</span><span class="sc">:</span><span class="dv">366</span>,</span>
<span id="cb72-4"><a href="regressions.html#cb72-4" aria-hidden="true" tabindex="-1"></a>                                       prism<span class="sc">$</span>years)</span>
<span id="cb72-5"><a href="regressions.html#cb72-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-6"><a href="regressions.html#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="co"># converting 3D matrxi to a dataframe:</span></span>
<span id="cb72-7"><a href="regressions.html#cb72-7" aria-hidden="true" tabindex="-1"></a>tmaxdf <span class="ot">&lt;-</span> <span class="fu">as.data.frame.table</span>(prism<span class="sc">$</span>tmaxdaily.iowa)</span>
<span id="cb72-8"><a href="regressions.html#cb72-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-9"><a href="regressions.html#cb72-9" aria-hidden="true" tabindex="-1"></a><span class="co"># relabel the columns</span></span>
<span id="cb72-10"><a href="regressions.html#cb72-10" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(tmaxdf) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;countyfp&quot;</span>,<span class="st">&quot;doy&quot;</span>,<span class="st">&quot;year&quot;</span>,<span class="st">&quot;tmax&quot;</span>)</span>
<span id="cb72-11"><a href="regressions.html#cb72-11" aria-hidden="true" tabindex="-1"></a>tmaxdf <span class="ot">&lt;-</span> <span class="fu">tibble</span>(tmaxdf) <span class="co"># tidying up</span></span></code></pre></div>
</div>
<div id="temperature-trends" class="section level3 hasAnchor" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Temperature Trends<a href="regressions.html#temperature-trends" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="summer-temperature-trends-winneshiek-county" class="section level4 hasAnchor" number="7.1.2.1">
<h4><span class="header-section-number">7.1.2.1</span> Summer Temperature Trends: Winneshiek County<a href="regressions.html#summer-temperature-trends-winneshiek-county" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="regressions.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># converting some factors into dbl:</span></span>
<span id="cb73-2"><a href="regressions.html#cb73-2" aria-hidden="true" tabindex="-1"></a>tmaxdf<span class="sc">$</span>doy <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(tmaxdf<span class="sc">$</span>doy)</span>
<span id="cb73-3"><a href="regressions.html#cb73-3" aria-hidden="true" tabindex="-1"></a>tmaxdf<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(tmaxdf<span class="sc">$</span>year))</span>
<span id="cb73-4"><a href="regressions.html#cb73-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-5"><a href="regressions.html#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="co"># creating variable for containing summer temp values of county 191</span></span>
<span id="cb73-6"><a href="regressions.html#cb73-6" aria-hidden="true" tabindex="-1"></a>winnesummer <span class="ot">&lt;-</span> tmaxdf <span class="sc">%&gt;%</span></span>
<span id="cb73-7"><a href="regressions.html#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(countyfp <span class="sc">==</span> <span class="dv">191</span> <span class="sc">&amp;</span> doy <span class="sc">&gt;=</span> <span class="dv">152</span> <span class="sc">&amp;</span> doy <span class="sc">&lt;=</span> <span class="dv">243</span>) <span class="sc">%&gt;%</span></span>
<span id="cb73-8"><a href="regressions.html#cb73-8" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(year)<span class="sc">%&gt;%</span></span>
<span id="cb73-9"><a href="regressions.html#cb73-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">meantmax =</span> <span class="fu">mean</span>(tmax))</span></code></pre></div>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="regressions.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(winnesummer, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> meantmax))<span class="sc">+</span></span>
<span id="cb74-2"><a href="regressions.html#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb74-3"><a href="regressions.html#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb74-4"><a href="regressions.html#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;year&quot;</span>, <span class="at">y =</span> <span class="st">&#39;Maximum Temperature (°C)&#39;</span>)<span class="sc">+</span></span>
<span id="cb74-5"><a href="regressions.html#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Average Daily Max Summer Temperature for Winneshiek County, Iowa&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/17%20plotting%20summer%20temps-1.png" width="672" /></p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="regressions.html#cb75-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)</span></code></pre></div>
<pre><code>## geom_smooth: na.rm = FALSE, orientation = NA, se = TRUE
## stat_smooth: na.rm = FALSE, orientation = NA, se = TRUE, method = function (formula, data, subset, weights, na.action, method = &quot;qr&quot;, model = TRUE, x = FALSE, y = FALSE, qr = TRUE, singular.ok = TRUE, contrasts = NULL, offset, ...) 
## {
##     ret.x &lt;- x
##     ret.y &lt;- y
##     cl &lt;- match.call()
##     mf &lt;- match.call(expand.dots = FALSE)
##     m &lt;- match(c(&quot;formula&quot;, &quot;data&quot;, &quot;subset&quot;, &quot;weights&quot;, &quot;na.action&quot;, &quot;offset&quot;), names(mf), 0)
##     mf &lt;- mf[c(1, m)]
##     mf$drop.unused.levels &lt;- TRUE
##     mf[[1]] &lt;- quote(stats::model.frame)
##     mf &lt;- eval(mf, parent.frame())
##     if (method == &quot;model.frame&quot;) 
##         return(mf)
##     else if (method != &quot;qr&quot;) 
##         warning(gettextf(&quot;method = &#39;%s&#39; is not supported. Using &#39;qr&#39;&quot;, method), domain = NA)
##     mt &lt;- attr(mf, &quot;terms&quot;)
##     y &lt;- model.response(mf, &quot;numeric&quot;)
##     w &lt;- as.vector(model.weights(mf))
##     if (!is.null(w) &amp;&amp; !is.numeric(w)) 
##         stop(&quot;&#39;weights&#39; must be a numeric vector&quot;)
##     offset &lt;- model.offset(mf)
##     mlm &lt;- is.matrix(y)
##     ny &lt;- if (mlm) 
##         nrow(y)
##     else length(y)
##     if (!is.null(offset)) {
##         if (!mlm) 
##             offset &lt;- as.vector(offset)
##         if (NROW(offset) != ny) 
##             stop(gettextf(&quot;number of offsets is %d, should equal %d (number of observations)&quot;, NROW(offset), ny), domain = NA)
##     }
##     if (is.empty.model(mt)) {
##         x &lt;- NULL
##         z &lt;- list(coefficients = if (mlm) matrix(NA, 0, ncol(y)) else numeric(), residuals = y, fitted.values = 0 * y, weights = w, rank = 0, df.residual = if (!is.null(w)) sum(w != 0) else ny)
##         if (!is.null(offset)) {
##             z$fitted.values &lt;- offset
##             z$residuals &lt;- y - offset
##         }
##     }
##     else {
##         x &lt;- model.matrix(mt, mf, contrasts)
##         z &lt;- if (is.null(w)) 
##             lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...)
##         else lm.wfit(x, y, w, offset = offset, singular.ok = singular.ok, ...)
##     }
##     class(z) &lt;- c(if (mlm) &quot;mlm&quot;, &quot;lm&quot;)
##     z$na.action &lt;- attr(mf, &quot;na.action&quot;)
##     z$offset &lt;- offset
##     z$contrasts &lt;- attr(x, &quot;contrasts&quot;)
##     z$xlevels &lt;- .getXlevels(mt, mf)
##     z$call &lt;- cl
##     z$terms &lt;- mt
##     if (model) 
##         z$model &lt;- mf
##     if (ret.x) 
##         z$x &lt;- x
##     if (ret.y) 
##         z$y &lt;- y
##     if (!qr) 
##         z$qr &lt;- NULL
##     z
## }
## position_identity</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="regressions.html#cb77-1" aria-hidden="true" tabindex="-1"></a>lm_summertmax <span class="ot">&lt;-</span> <span class="fu">lm</span>(meantmax <span class="sc">~</span> year, winnesummer)</span>
<span id="cb77-2"><a href="regressions.html#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_summertmax)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = meantmax ~ year, data = winnesummer)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.5189 -0.7867 -0.0341  0.6859  3.7415 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 41.57670   36.44848   1.141    0.262
## year        -0.00747    0.01823  -0.410    0.684
## 
## Residual standard error: 1.232 on 36 degrees of freedom
## Multiple R-squared:  0.004644,   Adjusted R-squared:  -0.02301 
## F-statistic: 0.168 on 1 and 36 DF,  p-value: 0.6844</code></pre>
</div>
<div id="winter-temperatures-trends-winneshek-county" class="section level4 hasAnchor" number="7.1.2.2">
<h4><span class="header-section-number">7.1.2.2</span> Winter Temperatures trends: Winneshek County<a href="regressions.html#winter-temperatures-trends-winneshek-county" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="regressions.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creating variable for containing winter temp values of county 191</span></span>
<span id="cb79-2"><a href="regressions.html#cb79-2" aria-hidden="true" tabindex="-1"></a>winnewinter <span class="ot">&lt;-</span> tmaxdf <span class="sc">%&gt;%</span></span>
<span id="cb79-3"><a href="regressions.html#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(countyfp <span class="sc">==</span> <span class="dv">191</span> <span class="sc">&amp;</span> (doy <span class="sc">&lt;=</span> <span class="dv">59</span> <span class="sc">|</span> doy <span class="sc">&gt;=</span> <span class="dv">335</span>) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(tmax)) <span class="sc">%&gt;%</span></span>
<span id="cb79-4"><a href="regressions.html#cb79-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(year)<span class="sc">%&gt;%</span></span>
<span id="cb79-5"><a href="regressions.html#cb79-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">meantmax =</span> <span class="fu">mean</span>(tmax))</span></code></pre></div>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="regressions.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(winnewinter, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> meantmax))<span class="sc">+</span></span>
<span id="cb80-2"><a href="regressions.html#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb80-3"><a href="regressions.html#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb80-4"><a href="regressions.html#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Average Daily Max Winter Temperature (°C)&quot;</span>)<span class="sc">+</span></span>
<span id="cb80-5"><a href="regressions.html#cb80-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&#39;Average Daily Max Temperature in Winter for Winneshiek County, Iowa&#39;</span>)<span class="sc">+</span></span>
<span id="cb80-6"><a href="regressions.html#cb80-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/19%20plotting%20winter%20temps%20for%20Winneshek-1.png" width="672" /></p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="regressions.html#cb81-1" aria-hidden="true" tabindex="-1"></a>lm_wintertmax <span class="ot">&lt;-</span> <span class="fu">lm</span>(meantmax <span class="sc">~</span> year, winnewinter)</span>
<span id="cb81-2"><a href="regressions.html#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_wintertmax)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = meantmax ~ year, data = winnewinter)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.5978 -1.4917 -0.3053  1.3778  4.5709 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -29.87825   60.48100  -0.494    0.624
## year          0.01368    0.03025   0.452    0.654
## 
## Residual standard error: 2.045 on 36 degrees of freedom
## Multiple R-squared:  0.005652,   Adjusted R-squared:  -0.02197 
## F-statistic: 0.2046 on 1 and 36 DF,  p-value: 0.6537</code></pre>
</div>
</div>
<div id="multiple-regression-quadratic-time-trend" class="section level3 hasAnchor" number="7.1.3">
<h3><span class="header-section-number">7.1.3</span> Multiple Regression – Quadratic Time Trend<a href="regressions.html#multiple-regression-quadratic-time-trend" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="regressions.html#cb83-1" aria-hidden="true" tabindex="-1"></a>winnewinter<span class="sc">$</span>yearsq <span class="ot">&lt;-</span> winnewinter<span class="sc">$</span>year<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb83-2"><a href="regressions.html#cb83-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-3"><a href="regressions.html#cb83-3" aria-hidden="true" tabindex="-1"></a>lm_wintertmaxquad <span class="ot">&lt;-</span> <span class="fu">lm</span>(meantmax <span class="sc">~</span> year <span class="sc">+</span> yearsq, winnewinter)</span>
<span id="cb83-4"><a href="regressions.html#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(lm_winntertmaxquad)</span></span>
<span id="cb83-5"><a href="regressions.html#cb83-5" aria-hidden="true" tabindex="-1"></a>winnewinter<span class="sc">$</span>fitted <span class="ot">&lt;-</span> lm_wintertmaxquad<span class="sc">$</span>fitted.values</span>
<span id="cb83-6"><a href="regressions.html#cb83-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-7"><a href="regressions.html#cb83-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(winnewinter)<span class="sc">+</span></span>
<span id="cb83-8"><a href="regressions.html#cb83-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> meantmax)) <span class="sc">+</span></span>
<span id="cb83-9"><a href="regressions.html#cb83-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> fitted))<span class="sc">+</span></span>
<span id="cb83-10"><a href="regressions.html#cb83-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb83-11"><a href="regressions.html#cb83-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Average Daily Max Winter Temperature (°C)&quot;</span>)<span class="sc">+</span> </span>
<span id="cb83-12"><a href="regressions.html#cb83-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Average Max Daily Winter Temperature for Winneshiek County, Iowa&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
</div>
<div id="download-nass-corn-yield-data" class="section level3 hasAnchor" number="7.1.4">
<h3><span class="header-section-number">7.1.4</span> Download NASS corn yield data<a href="regressions.html#download-nass-corn-yield-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="regressions.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="do">## set our API key with NASS</span></span>
<span id="cb84-2"><a href="regressions.html#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nassqs_auth</span>(<span class="at">key =</span> <span class="st">&quot;6C0A99BB-3CB7-3E99-A699-B9DB7FDB8D16&quot;</span>)</span>
<span id="cb84-3"><a href="regressions.html#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="regressions.html#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="do">## parameters to query on</span></span>
<span id="cb84-5"><a href="regressions.html#cb84-5" aria-hidden="true" tabindex="-1"></a>params <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">commodity_desc =</span> <span class="st">&quot;CORN&quot;</span>, <span class="at">util_practice_desc =</span> <span class="st">&quot;GRAIN&quot;</span>,</span>
<span id="cb84-6"><a href="regressions.html#cb84-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">prodn_practice_desc =</span> <span class="st">&quot;ALL PRODUCTION PRACTICES&quot;</span>,</span>
<span id="cb84-7"><a href="regressions.html#cb84-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">year__GE =</span> <span class="dv">1981</span>, <span class="at">state_alpha =</span> <span class="st">&quot;IA&quot;</span>)</span>
<span id="cb84-8"><a href="regressions.html#cb84-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-9"><a href="regressions.html#cb84-9" aria-hidden="true" tabindex="-1"></a><span class="co"># download</span></span>
<span id="cb84-10"><a href="regressions.html#cb84-10" aria-hidden="true" tabindex="-1"></a>cornyieldsall <span class="ot">&lt;-</span> <span class="fu">nassqs_yields</span>(params)</span>
<span id="cb84-11"><a href="regressions.html#cb84-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-12"><a href="regressions.html#cb84-12" aria-hidden="true" tabindex="-1"></a><span class="co">#convert to numeric</span></span>
<span id="cb84-13"><a href="regressions.html#cb84-13" aria-hidden="true" tabindex="-1"></a>cornyieldsall<span class="sc">$</span>county_ansi <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(cornyieldsall<span class="sc">$</span>county_ansi)</span>
<span id="cb84-14"><a href="regressions.html#cb84-14" aria-hidden="true" tabindex="-1"></a>cornyieldsall<span class="sc">$</span>yield <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(cornyieldsall<span class="sc">$</span>Value)</span>
<span id="cb84-15"><a href="regressions.html#cb84-15" aria-hidden="true" tabindex="-1"></a>cornyieldsall<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(cornyieldsall<span class="sc">$</span>year)</span></code></pre></div>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="regressions.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#clean and filter dataset</span></span>
<span id="cb85-2"><a href="regressions.html#cb85-2" aria-hidden="true" tabindex="-1"></a>cornyields <span class="ot">&lt;-</span> <span class="fu">select</span>(cornyieldsall,county_ansi, </span>
<span id="cb85-3"><a href="regressions.html#cb85-3" aria-hidden="true" tabindex="-1"></a>                     county_name, yield, year)<span class="sc">%&gt;%</span></span>
<span id="cb85-4"><a href="regressions.html#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(county_ansi) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(yield))</span>
<span id="cb85-5"><a href="regressions.html#cb85-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-6"><a href="regressions.html#cb85-6" aria-hidden="true" tabindex="-1"></a><span class="co"># make a tibble</span></span>
<span id="cb85-7"><a href="regressions.html#cb85-7" aria-hidden="true" tabindex="-1"></a>cornyields <span class="ot">&lt;-</span> <span class="fu">tibble</span>(cornyields)</span></code></pre></div>
</div>
</div>
<div id="assignment-3" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Assignment<a href="regressions.html#assignment-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="question-1a-extract-winneshiek-county-corn-yields-fit-a-linear-time-trend-make-a-plot.-is-there-a-significant-time-trend" class="section level3 hasAnchor" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> Question 1a: Extract Winneshiek County corn yields, fit a linear time trend, make a plot. Is there a significant time trend?<a href="regressions.html#question-1a-extract-winneshiek-county-corn-yields-fit-a-linear-time-trend-make-a-plot.-is-there-a-significant-time-trend" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="regressions.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sifting out to have only the Winneshiek data</span></span>
<span id="cb86-2"><a href="regressions.html#cb86-2" aria-hidden="true" tabindex="-1"></a>wnnshk_uncln <span class="ot">&lt;-</span> cornyields <span class="sc">%&gt;%</span></span>
<span id="cb86-3"><a href="regressions.html#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(county_name <span class="sc">==</span> <span class="st">&quot;WINNESHIEK&quot;</span>)</span>
<span id="cb86-4"><a href="regressions.html#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="co">#making sure that there aren&#39;t any rows with NAs:</span></span>
<span id="cb86-5"><a href="regressions.html#cb86-5" aria-hidden="true" tabindex="-1"></a>wnnshk <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(wnnshk_uncln) </span></code></pre></div>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="regressions.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting linear regression for time trend:</span></span>
<span id="cb87-2"><a href="regressions.html#cb87-2" aria-hidden="true" tabindex="-1"></a>lm_wnnshk <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> year, <span class="at">data =</span> wnnshk)</span>
<span id="cb87-3"><a href="regressions.html#cb87-3" aria-hidden="true" tabindex="-1"></a>wnnshk<span class="sc">$</span>linear <span class="ot">&lt;-</span> lm_wnnshk<span class="sc">$</span>fitted.values</span>
<span id="cb87-4"><a href="regressions.html#cb87-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-5"><a href="regressions.html#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_wnnshk)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ year, data = wnnshk)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -51.163  -1.841   2.363   9.437  24.376 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -4763.290    448.286  -10.63 4.46e-13 ***
## year            2.457      0.224   10.96 1.77e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 16.97 on 39 degrees of freedom
## Multiple R-squared:  0.7551, Adjusted R-squared:  0.7488 
## F-statistic: 120.2 on 1 and 39 DF,  p-value: 1.767e-13</code></pre>
<p>According the summary statistics for the linear regression model fitted to the yield ~ year data for Winneshiek, there is indeed a quite significant time trend. The slope has a value of 2.457 yield units increase per year, and the p-value for that slope is 1.77e-13.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="regressions.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting yield ~ time along with linear regression:</span></span>
<span id="cb89-2"><a href="regressions.html#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wnnshk) <span class="sc">+</span></span>
<span id="cb89-3"><a href="regressions.html#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb89-4"><a href="regressions.html#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> linear)) <span class="sc">+</span></span>
<span id="cb89-5"><a href="regressions.html#cb89-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb89-6"><a href="regressions.html#cb89-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;yield (bu/acre)&quot;</span>)<span class="sc">+</span></span>
<span id="cb89-7"><a href="regressions.html#cb89-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Corn Yield in Winneshiek County, Iowa&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
</div>
<div id="question-1b-fit-a-quadratic-time-trend-i.e.-year-year2-and-make-a-plot.-is-there-evidence-for-slowing-yield-growth" class="section level3 hasAnchor" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> Question 1b: Fit a quadratic time trend (i.e., year + year^2) and make a plot. Is there evidence for slowing yield growth?<a href="regressions.html#question-1b-fit-a-quadratic-time-trend-i.e.-year-year2-and-make-a-plot.-is-there-evidence-for-slowing-yield-growth" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="regressions.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Fitting quadratic time trend</span></span>
<span id="cb90-2"><a href="regressions.html#cb90-2" aria-hidden="true" tabindex="-1"></a>wnnshk<span class="sc">$</span>yearsq <span class="ot">&lt;-</span> wnnshk<span class="sc">$</span>year<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb90-3"><a href="regressions.html#cb90-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-4"><a href="regressions.html#cb90-4" aria-hidden="true" tabindex="-1"></a>qd_wnnshk <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> (year <span class="sc">+</span> yearsq), <span class="at">data =</span> wnnshk)</span>
<span id="cb90-5"><a href="regressions.html#cb90-5" aria-hidden="true" tabindex="-1"></a>wnnshk<span class="sc">$</span>quadratic <span class="ot">&lt;-</span> qd_wnnshk<span class="sc">$</span>fitted.values</span>
<span id="cb90-6"><a href="regressions.html#cb90-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-7"><a href="regressions.html#cb90-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(qd_wnnshk)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ (year + yearsq), data = wnnshk)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -51.384  -3.115   1.388   9.743  25.324 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  2.583e+04  8.580e+04   0.301    0.765
## year        -2.812e+01  8.576e+01  -0.328    0.745
## yearsq       7.641e-03  2.143e-02   0.357    0.723
## 
## Residual standard error: 17.17 on 38 degrees of freedom
## Multiple R-squared:  0.7559, Adjusted R-squared:  0.7431 
## F-statistic: 58.84 on 2 and 38 DF,  p-value: 2.311e-12</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="regressions.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="do">## plotting quadratic transform:</span></span>
<span id="cb92-2"><a href="regressions.html#cb92-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-3"><a href="regressions.html#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wnnshk) <span class="sc">+</span></span>
<span id="cb92-4"><a href="regressions.html#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> yield)) <span class="sc">+</span> </span>
<span id="cb92-5"><a href="regressions.html#cb92-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> quadratic))<span class="sc">+</span></span>
<span id="cb92-6"><a href="regressions.html#cb92-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;yield (bu/acre)&quot;</span>)<span class="sc">+</span></span>
<span id="cb92-7"><a href="regressions.html#cb92-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&#39;Corn Yield in Winneshiek County, Iowa&#39;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<p>In the summary statistics for the quadratic regression model, we see that the coefficient for yearsq is 7.641e-03, a positive value, but it’s p-value is large at 0.723. Due to this large p-value, we conclude that the quadratic regression model does not fit the data well. We do not have evidence that yields are either slowing or growing with each year.</p>
<p><em>If the p-value were small (&lt; 0.05), we would conclude that yields are growing with each year, due to the fact that the yearsq coefficient is positive – meaning that the model is U-shaped rather than n-shaped – and that the data would clearly be the right-side of the U (as the plot makes obvious).</em></p>
</div>
<div id="question-2-time-series-lets-analyze-the-relationship-between-temperature-and-yields-for-the-winneshiek-county-time-series.-use-data-on-yield-and-summer-avg-tmax.-is-adding-year-or-tmax2-to-your-model-helpful-make-a-plot-and-interpret-the-results." class="section level3 hasAnchor" number="7.2.3">
<h3><span class="header-section-number">7.2.3</span> Question 2 – Time Series: Let’s analyze the relationship between temperature and yields for the Winneshiek County time series. Use data on yield and summer avg Tmax. Is adding year or Tmax^2 to your model helpful? Make a plot and interpret the results.<a href="regressions.html#question-2-time-series-lets-analyze-the-relationship-between-temperature-and-yields-for-the-winneshiek-county-time-series.-use-data-on-yield-and-summer-avg-tmax.-is-adding-year-or-tmax2-to-your-model-helpful-make-a-plot-and-interpret-the-results." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="regressions.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Joining the yield data to the temp data.</span></span>
<span id="cb94-2"><a href="regressions.html#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="do">## (Note:  temp data ends at 2018 and yield goes to 2021.)</span></span>
<span id="cb94-3"><a href="regressions.html#cb94-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-4"><a href="regressions.html#cb94-4" aria-hidden="true" tabindex="-1"></a>wnnshk_ty <span class="ot">&lt;-</span> <span class="fu">left_join</span>(winnesummer, wnnshk, <span class="at">by =</span> <span class="st">&#39;year&#39;</span>)<span class="sc">%&gt;%</span></span>
<span id="cb94-5"><a href="regressions.html#cb94-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(yield), <span class="sc">!</span><span class="fu">is.na</span>(meantmax))</span></code></pre></div>
<div id="first-looking-at-the-linear-model-for-yield-meantmax" class="section level4 hasAnchor" number="7.2.3.1">
<h4><span class="header-section-number">7.2.3.1</span> First Looking at the Linear Model for Yield ~ MeanTmax<a href="regressions.html#first-looking-at-the-linear-model-for-yield-meantmax" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="regressions.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating linear model for analyzing Yield ~ meanTmax:</span></span>
<span id="cb95-2"><a href="regressions.html#cb95-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-3"><a href="regressions.html#cb95-3" aria-hidden="true" tabindex="-1"></a>lm_w_ty <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> meantmax, <span class="at">data =</span> wnnshk_ty)</span>
<span id="cb95-4"><a href="regressions.html#cb95-4" aria-hidden="true" tabindex="-1"></a>wnnshk_ty<span class="sc">$</span>lin_ty <span class="ot">&lt;-</span> lm_w_ty<span class="sc">$</span>fitted.values</span>
<span id="cb95-5"><a href="regressions.html#cb95-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-6"><a href="regressions.html#cb95-6" aria-hidden="true" tabindex="-1"></a><span class="co"># summary stats for linear model</span></span>
<span id="cb95-7"><a href="regressions.html#cb95-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_w_ty)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ meantmax, data = wnnshk_ty)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -71.96 -19.85  -3.19  24.64  61.72 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  275.876    118.335   2.331   0.0255 *
## meantmax      -4.763      4.438  -1.073   0.2902  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 32.88 on 36 degrees of freedom
## Multiple R-squared:  0.03101,    Adjusted R-squared:  0.004098 
## F-statistic: 1.152 on 1 and 36 DF,  p-value: 0.2902</code></pre>
<p><strong><em>Note: The summary statistics for the linear model prove that it is not a good fit for this data. The p-value for the coefficient of meantmax is 0.2902, which is much greater than 0.05.</em></strong></p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="regressions.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting linear model</span></span>
<span id="cb97-2"><a href="regressions.html#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wnnshk_ty) <span class="sc">+</span></span>
<span id="cb97-3"><a href="regressions.html#cb97-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb97-4"><a href="regressions.html#cb97-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> lin_ty)) <span class="sc">+</span></span>
<span id="cb97-5"><a href="regressions.html#cb97-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb97-6"><a href="regressions.html#cb97-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Average Daily Maximum Summer Temperature (°C)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Corn Yield (bu/acre)&quot;</span>)<span class="sc">+</span></span>
<span id="cb97-7"><a href="regressions.html#cb97-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Corn Yield vs. Average Daily Max Summer Temperature&quot;</span>, </span>
<span id="cb97-8"><a href="regressions.html#cb97-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">subtitle =</span> <span class="st">&quot;Winneshiek County, Iowa&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
</div>
<div id="second-examining-the-quadratic-model-for-yield-meantmax2-meantmax" class="section level4 hasAnchor" number="7.2.3.2">
<h4><span class="header-section-number">7.2.3.2</span> Second, Examining the Quadratic Model for Yield ~ (MeanTmax^2 + MeanTmax)<a href="regressions.html#second-examining-the-quadratic-model-for-yield-meantmax2-meantmax" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="regressions.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating quadratic model for analyzing Yield ~ (Tmax^2 + Tmax)</span></span>
<span id="cb98-2"><a href="regressions.html#cb98-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-3"><a href="regressions.html#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="do">## first creating meantmaxsq data:</span></span>
<span id="cb98-4"><a href="regressions.html#cb98-4" aria-hidden="true" tabindex="-1"></a>wnnshk_ty<span class="sc">$</span>meantmaxsq <span class="ot">&lt;-</span> wnnshk_ty<span class="sc">$</span>meantmax<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb98-5"><a href="regressions.html#cb98-5" aria-hidden="true" tabindex="-1"></a><span class="do">## now generating quadratic model: </span></span>
<span id="cb98-6"><a href="regressions.html#cb98-6" aria-hidden="true" tabindex="-1"></a>qd_w_ty <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> (meantmax <span class="sc">+</span> meantmaxsq), <span class="at">data =</span> wnnshk_ty)</span>
<span id="cb98-7"><a href="regressions.html#cb98-7" aria-hidden="true" tabindex="-1"></a><span class="do">## pulling fitted values from quadratic model and adding to dataframe:</span></span>
<span id="cb98-8"><a href="regressions.html#cb98-8" aria-hidden="true" tabindex="-1"></a>wnnshk_ty<span class="sc">$</span>qd_ty <span class="ot">&lt;-</span> qd_w_ty<span class="sc">$</span>fitted.values</span>
<span id="cb98-9"><a href="regressions.html#cb98-9" aria-hidden="true" tabindex="-1"></a><span class="do">## looking at the quadratic model&#39;s summary statistics:</span></span>
<span id="cb98-10"><a href="regressions.html#cb98-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(qd_w_ty)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ (meantmax + meantmaxsq), data = wnnshk_ty)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -56.587 -22.262  -0.982  22.409  52.798 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept) -4223.604   1446.639  -2.920  0.00609 **
## meantmax      328.918    107.068   3.072  0.00410 **
## meantmaxsq     -6.173      1.979  -3.119  0.00362 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 29.5 on 35 degrees of freedom
## Multiple R-squared:  0.2417, Adjusted R-squared:  0.1984 
## F-statistic: 5.579 on 2 and 35 DF,  p-value: 0.007887</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="regressions.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting quadratic model</span></span>
<span id="cb100-2"><a href="regressions.html#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wnnshk_ty)<span class="sc">+</span></span>
<span id="cb100-3"><a href="regressions.html#cb100-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb100-4"><a href="regressions.html#cb100-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> qd_ty))<span class="sc">+</span></span>
<span id="cb100-5"><a href="regressions.html#cb100-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb100-6"><a href="regressions.html#cb100-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Average Daily Max Summer Temperature (°C)&quot;</span>, </span>
<span id="cb100-7"><a href="regressions.html#cb100-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Corn Yield (bu/acre)&quot;</span>)<span class="sc">+</span></span>
<span id="cb100-8"><a href="regressions.html#cb100-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Corn Yield vs. Average Daily Max Summer Temperature&quot;</span>, </span>
<span id="cb100-9"><a href="regressions.html#cb100-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">subtitle =</span> <span class="st">&quot;Winneshiek County, Iowa&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<p>The summary statistics for the quadratic regression model for Yield ~ (meantmax^2 + meantmax) shows that the quadratic model is indeed helpful for understanding the trend of the data. We can tell this by looking at the p-values for coefficients of meantmax, meantmaxsq, and the intercept, all of which are quite small and substantially lower than 0.05.</p>
<p>The plot of this quadratic model, as shown above, clearly displays a negative parabolic curve (which regression model’s summary statistics also indicated). This type of relationship was to be expected, as optimum temperatures for maximizing yields must be neither too low nor too high.</p>
<p>The quadratic model for this data should be accepted, while the linear model should be rejected.</p>
</div>
</div>
<div id="question-3-cross-section-analyze-the-relationship-between-temperature-and-yield-across-all-counties-in-2018.-is-there-a-relationship-interpret-the-results." class="section level3 hasAnchor" number="7.2.4">
<h3><span class="header-section-number">7.2.4</span> Question 3 – Cross-Section: Analyze the relationship between temperature and yield across all counties in 2018. Is there a relationship? Interpret the results.<a href="regressions.html#question-3-cross-section-analyze-the-relationship-between-temperature-and-yield-across-all-counties-in-2018.-is-there-a-relationship-interpret-the-results." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="regressions.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering down the temperature data to only what we need...</span></span>
<span id="cb102-2"><a href="regressions.html#cb102-2" aria-hidden="true" tabindex="-1"></a>t_18 <span class="ot">&lt;-</span> tmaxdf <span class="sc">%&gt;%</span></span>
<span id="cb102-3"><a href="regressions.html#cb102-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2018</span>, (doy <span class="sc">&gt;</span> <span class="dv">151</span> <span class="sc">&amp;</span> doy <span class="sc">&lt;</span> <span class="dv">244</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb102-4"><a href="regressions.html#cb102-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ...then grouping by county...</span></span>
<span id="cb102-5"><a href="regressions.html#cb102-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(countyfp) <span class="sc">%&gt;%</span></span>
<span id="cb102-6"><a href="regressions.html#cb102-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ...and calculating meanTmax for each county</span></span>
<span id="cb102-7"><a href="regressions.html#cb102-7" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">meantmax =</span> <span class="fu">mean</span>(tmax)) </span>
<span id="cb102-8"><a href="regressions.html#cb102-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-9"><a href="regressions.html#cb102-9" aria-hidden="true" tabindex="-1"></a><span class="co"># going ahead and converting countyfp to numeric:</span></span>
<span id="cb102-10"><a href="regressions.html#cb102-10" aria-hidden="true" tabindex="-1"></a>t_18<span class="sc">$</span>countyfp <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(t_18<span class="sc">$</span>countyfp))</span></code></pre></div>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="regressions.html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering down cornyields data to only 2018</span></span>
<span id="cb103-2"><a href="regressions.html#cb103-2" aria-hidden="true" tabindex="-1"></a>cy_18 <span class="ot">&lt;-</span> cornyields <span class="sc">%&gt;%</span></span>
<span id="cb103-3"><a href="regressions.html#cb103-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2018</span>, </span>
<span id="cb103-4"><a href="regressions.html#cb103-4" aria-hidden="true" tabindex="-1"></a>         <span class="co"># making sure all NA&#39;s are gone</span></span>
<span id="cb103-5"><a href="regressions.html#cb103-5" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(yield), <span class="sc">!</span><span class="fu">is.na</span>(county_name),<span class="sc">!</span><span class="fu">is.na</span>(county_ansi)) <span class="sc">%&gt;%</span></span>
<span id="cb103-6"><a href="regressions.html#cb103-6" aria-hidden="true" tabindex="-1"></a>        <span class="co"># creating countyfp column in preparation for joining</span></span>
<span id="cb103-7"><a href="regressions.html#cb103-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">countyfp =</span> county_ansi)</span></code></pre></div>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="regressions.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Joining t_18 to cy_18, and selecting down to meantmax, yield, countyfp</span></span>
<span id="cb104-2"><a href="regressions.html#cb104-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-3"><a href="regressions.html#cb104-3" aria-hidden="true" tabindex="-1"></a>tcy_18 <span class="ot">&lt;-</span> <span class="fu">left_join</span>(cy_18,t_18, <span class="at">by =</span> <span class="st">&quot;countyfp&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb104-4"><a href="regressions.html#cb104-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(countyfp, meantmax, yield) <span class="sc">%&gt;%</span></span>
<span id="cb104-5"><a href="regressions.html#cb104-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(countyfp),<span class="sc">!</span><span class="fu">is.na</span>(meantmax),<span class="sc">!</span><span class="fu">is.na</span>(yield))</span></code></pre></div>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="regressions.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating quadratic regression model</span></span>
<span id="cb105-2"><a href="regressions.html#cb105-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-3"><a href="regressions.html#cb105-3" aria-hidden="true" tabindex="-1"></a><span class="do">## calculating meantmaxsq values</span></span>
<span id="cb105-4"><a href="regressions.html#cb105-4" aria-hidden="true" tabindex="-1"></a>tcy_18<span class="sc">$</span>meantmaxsq <span class="ot">&lt;-</span> tcy_18<span class="sc">$</span>meantmax<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb105-5"><a href="regressions.html#cb105-5" aria-hidden="true" tabindex="-1"></a><span class="do">## creating quadratic model</span></span>
<span id="cb105-6"><a href="regressions.html#cb105-6" aria-hidden="true" tabindex="-1"></a>qd_tcy_18 <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> (meantmaxsq <span class="sc">+</span> meantmax), tcy_18)</span>
<span id="cb105-7"><a href="regressions.html#cb105-7" aria-hidden="true" tabindex="-1"></a><span class="do">## adding model&#39;s values to tcy_18 dataframe</span></span>
<span id="cb105-8"><a href="regressions.html#cb105-8" aria-hidden="true" tabindex="-1"></a>tcy_18<span class="sc">$</span>qd_yvalues <span class="ot">&lt;-</span> qd_tcy_18<span class="sc">$</span>fitted.values</span>
<span id="cb105-9"><a href="regressions.html#cb105-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-10"><a href="regressions.html#cb105-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(qd_tcy_18)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ (meantmaxsq + meantmax), data = tcy_18)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -44.221 -15.399   5.007  14.541  30.879 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept) -5501.602   1860.830  -2.957  0.00397 **
## meantmaxsq     -7.256      2.321  -3.126  0.00239 **
## meantmax      406.789    131.493   3.094  0.00263 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.75 on 90 degrees of freedom
## Multiple R-squared:  0.1317, Adjusted R-squared:  0.1124 
## F-statistic: 6.827 on 2 and 90 DF,  p-value: 0.001736</code></pre>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="regressions.html#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Saving fitted values for plotting</span></span></code></pre></div>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="regressions.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting Yield ~ MeanTmax for 2018 (all Iowa counties)</span></span>
<span id="cb108-2"><a href="regressions.html#cb108-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-3"><a href="regressions.html#cb108-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tcy_18) <span class="sc">+</span></span>
<span id="cb108-4"><a href="regressions.html#cb108-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield))<span class="sc">+</span></span>
<span id="cb108-5"><a href="regressions.html#cb108-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> qd_yvalues))<span class="sc">+</span></span>
<span id="cb108-6"><a href="regressions.html#cb108-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb108-7"><a href="regressions.html#cb108-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Average Daily Max Summer Temperature (°C)&quot;</span>, </span>
<span id="cb108-8"><a href="regressions.html#cb108-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Corn Yield (bu/acre)&quot;</span>,</span>
<span id="cb108-9"><a href="regressions.html#cb108-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Corn Yield vs. Average Daily Max Summer Temp by Iowa County&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
<p>We would expect that the relationship between mean summer maximum daily temperatures and corn yields across all Iowa counties for the year of 2018 would be very similar to the relationship between the same variables for Winneshiek County across all years (shown in the previous question). As such, we begin by fitting a quadratic model.</p>
<p>In the summary statistics for the quadratic regression model for (corn yield) ~ (meantmax^2 + meantmax), shown above, we can see that p-values for all coefficients are substantially less than 0.05. This indicates that the quadratic model does indeed fit well to the data. Further, we see that this model indicates that corn yields can be expected to be highest when the average maximum daily temperature for the summer months is 28°C.</p>
</div>
<div id="question-4-panel" class="section level3 hasAnchor" number="7.2.5">
<h3><span class="header-section-number">7.2.5</span> Question 4 – Panel:<a href="regressions.html#question-4-panel" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One way to leverage multiple time series is to group all data into what is called a “panel” regression. Convert the county ID code (“countyfp” or “county_ansi”) into factor using as.factor, then include this variable in a regression using all counties’ yield and summer temperature data.</p>
<p><strong>How does the significance of your temperature coefficients (Tmax, Tmax^2) change?</strong></p>
<p><strong>Make a plot comparing actual and fitted yields and interpret the results of your model.</strong></p>
<ul>
<li><em>Student’s question: are you asking me to create a plot that has actual yields on the y-axis and fitted yield on the x-axis? I’m not sure what you’re asking. It seems to me that what we really want is model that helps predict corn yields across all counties…</em></li>
</ul>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="regressions.html#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="do">## getting the temperature data:</span></span>
<span id="cb110-2"><a href="regressions.html#cb110-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-3"><a href="regressions.html#cb110-3" aria-hidden="true" tabindex="-1"></a><span class="do">### Filtering down the temperature data to only what we need...</span></span>
<span id="cb110-4"><a href="regressions.html#cb110-4" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> tmaxdf <span class="sc">%&gt;%</span></span>
<span id="cb110-5"><a href="regressions.html#cb110-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(doy <span class="sc">&gt;</span> <span class="dv">151</span> <span class="sc">&amp;</span> doy <span class="sc">&lt;</span> <span class="dv">244</span>) <span class="sc">%&gt;%</span></span>
<span id="cb110-6"><a href="regressions.html#cb110-6" aria-hidden="true" tabindex="-1"></a><span class="do">### ...then grouping by county...</span></span>
<span id="cb110-7"><a href="regressions.html#cb110-7" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(countyfp,year) <span class="sc">%&gt;%</span></span>
<span id="cb110-8"><a href="regressions.html#cb110-8" aria-hidden="true" tabindex="-1"></a><span class="do">### ...and calculating meanTmax for each county...</span></span>
<span id="cb110-9"><a href="regressions.html#cb110-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">meantmax =</span> <span class="fu">mean</span>(tmax)) <span class="sc">%&gt;%</span></span>
<span id="cb110-10"><a href="regressions.html#cb110-10" aria-hidden="true" tabindex="-1"></a><span class="do">### ...adding meantmaxsq in prep for quadratic regression model...</span></span>
<span id="cb110-11"><a href="regressions.html#cb110-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">meantmaxsq =</span> meantmax<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;countyfp&#39;. You can override using the
## `.groups` argument.</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="regressions.html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="do">## going ahead and converting countyfp to numeric:</span></span>
<span id="cb112-2"><a href="regressions.html#cb112-2" aria-hidden="true" tabindex="-1"></a>t<span class="sc">$</span>countyfp <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(t<span class="sc">$</span>countyfp))</span></code></pre></div>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="regressions.html#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the Yield Data</span></span>
<span id="cb113-2"><a href="regressions.html#cb113-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-3"><a href="regressions.html#cb113-3" aria-hidden="true" tabindex="-1"></a>cy <span class="ot">&lt;-</span> cornyields <span class="sc">%&gt;%</span></span>
<span id="cb113-4"><a href="regressions.html#cb113-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># making sure all NA&#39;s are gone</span></span>
<span id="cb113-5"><a href="regressions.html#cb113-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(yield), <span class="sc">!</span><span class="fu">is.na</span>(county_name),<span class="sc">!</span><span class="fu">is.na</span>(county_ansi)) <span class="sc">%&gt;%</span></span>
<span id="cb113-6"><a href="regressions.html#cb113-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># creating countyfp column in preparation for joining</span></span>
<span id="cb113-7"><a href="regressions.html#cb113-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">countyfp =</span> county_ansi)</span></code></pre></div>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="regressions.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Joining Temperature Data to Yield Data by county and year</span></span>
<span id="cb114-2"><a href="regressions.html#cb114-2" aria-hidden="true" tabindex="-1"></a>tcy <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(cy,t,<span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;countyfp&quot;</span>, <span class="st">&quot;year&quot;</span>))</span>
<span id="cb114-3"><a href="regressions.html#cb114-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-4"><a href="regressions.html#cb114-4" aria-hidden="true" tabindex="-1"></a><span class="do">## converting countyfp to factor (as instructed)</span></span>
<span id="cb114-5"><a href="regressions.html#cb114-5" aria-hidden="true" tabindex="-1"></a>tcy<span class="sc">$</span>countyfp <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(tcy<span class="sc">$</span>countyfp)</span>
<span id="cb114-6"><a href="regressions.html#cb114-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-7"><a href="regressions.html#cb114-7" aria-hidden="true" tabindex="-1"></a><span class="do">## cleaning out unneeded columns:</span></span>
<span id="cb114-8"><a href="regressions.html#cb114-8" aria-hidden="true" tabindex="-1"></a>tcy <span class="ot">&lt;-</span> <span class="fu">select</span>(tcy,<span class="sc">-</span><span class="fu">c</span>(<span class="st">&quot;county_ansi&quot;</span>, <span class="st">&quot;county_name&quot;</span>))</span>
<span id="cb114-9"><a href="regressions.html#cb114-9" aria-hidden="true" tabindex="-1"></a><span class="do">## reordering columns to proper positions:</span></span>
<span id="cb114-10"><a href="regressions.html#cb114-10" aria-hidden="true" tabindex="-1"></a>tcy <span class="ot">&lt;-</span> tcy[,<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">5</span>)]</span></code></pre></div>
<div id="first-attempting-the-panel-regression-as-instructed-without-using-the-panel-regression-function" class="section level4 hasAnchor" number="7.2.5.1">
<h4><span class="header-section-number">7.2.5.1</span> <strong>First attempting the panel regression as instructed, without using the panel regression function</strong><a href="regressions.html#first-attempting-the-panel-regression-as-instructed-without-using-the-panel-regression-function" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="regressions.html#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First creating lm() that does NOT factor in countyfp, but does factor both meantmax and meantmaxsq:</span></span>
<span id="cb115-2"><a href="regressions.html#cb115-2" aria-hidden="true" tabindex="-1"></a>panel_lm_NO_cfp <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> (meantmaxsq <span class="sc">+</span> meantmax), <span class="at">data =</span> tcy)</span>
<span id="cb115-3"><a href="regressions.html#cb115-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(panel_lm_NO_cfp)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ (meantmaxsq + meantmax), data = tcy)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -113.151  -21.982   -2.794   24.860   82.006 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -2098.6219   139.4315  -15.05   &lt;2e-16 ***
## meantmaxsq     -3.1665     0.1769  -17.90   &lt;2e-16 ***
## meantmax      168.9590     9.9402   17.00   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 31.55 on 3745 degrees of freedom
## Multiple R-squared:  0.1947, Adjusted R-squared:  0.1943 
## F-statistic: 452.8 on 2 and 3745 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="regressions.html#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating lm() that factors in meantmax, meantmaxsq, AND countyfp</span></span>
<span id="cb117-2"><a href="regressions.html#cb117-2" aria-hidden="true" tabindex="-1"></a>panel_lm_W_cfp <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> (meantmaxsq <span class="sc">+</span> meantmax <span class="sc">+</span> countyfp), <span class="at">data =</span> tcy)</span>
<span id="cb117-3"><a href="regressions.html#cb117-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(panel_lm_W_cfp)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ (meantmaxsq + meantmax + countyfp), data = tcy)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -95.088 -21.438  -3.026  23.570  77.941 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -2102.2327   139.2946 -15.092  &lt; 2e-16 ***
## meantmaxsq     -3.1324     0.1758 -17.820  &lt; 2e-16 ***
## meantmax      167.9699     9.8950  16.975  &lt; 2e-16 ***
## countyfp3      -4.5577     7.0388  -0.648 0.517347    
## countyfp5       1.9797     7.0743   0.280 0.779612    
## countyfp7     -19.1369     7.0864  -2.701 0.006955 ** 
## countyfp9       4.3024     7.0416   0.611 0.541240    
## countyfp11      6.2752     7.0459   0.891 0.373195    
## countyfp13      6.2028     7.0520   0.880 0.379147    
## countyfp15     14.3129     7.0414   2.033 0.042157 *  
## countyfp17     10.2595     7.0568   1.454 0.146076    
## countyfp19      6.6549     7.0596   0.943 0.345912    
## countyfp21      7.5427     7.0503   1.070 0.284760    
## countyfp23      8.0045     7.0493   1.135 0.256242    
## countyfp25      9.3627     7.0468   1.329 0.184048    
## countyfp27      8.8039     7.0426   1.250 0.211348    
## countyfp29      6.0858     7.0389   0.865 0.387315    
## countyfp31     14.9921     7.0443   2.128 0.033381 *  
## countyfp33      3.7400     7.0668   0.529 0.596677    
## countyfp35     12.8689     7.0455   1.827 0.067848 .  
## countyfp37      1.3837     7.0714   0.196 0.844876    
## countyfp39    -24.9874     7.0863  -3.526 0.000427 ***
## countyfp41      5.5213     7.0521   0.783 0.433716    
## countyfp43      7.9986     7.0648   1.132 0.257632    
## countyfp45      9.7142     7.0455   1.379 0.168043    
## countyfp47      5.5829     7.0436   0.793 0.428054    
## countyfp49     10.5962     7.0391   1.505 0.132323    
## countyfp51    -14.6474     7.0887  -2.066 0.038872 *  
## countyfp53    -16.7641     7.0865  -2.366 0.018051 *  
## countyfp55      8.6421     7.0667   1.223 0.221435    
## countyfp57     10.8382     7.0391   1.540 0.123719    
## countyfp59      2.0837     7.0635   0.295 0.768011    
## countyfp61      9.1371     7.0690   1.293 0.196245    
## countyfp63      6.4115     7.0706   0.907 0.364579    
## countyfp65      6.5576     7.0722   0.927 0.353862    
## countyfp67      3.8270     7.0595   0.542 0.587775    
## countyfp69     10.2572     7.0536   1.454 0.145983    
## countyfp71     15.9700     7.0526   2.264 0.023608 *  
## countyfp73     14.2209     7.0396   2.020 0.043445 *  
## countyfp75     10.3933     7.0506   1.474 0.140543    
## countyfp77      3.0582     7.0392   0.434 0.663988    
## countyfp79     12.1993     7.0442   1.732 0.083392 .  
## countyfp81      7.8892     7.0692   1.116 0.264496    
## countyfp83     13.0042     7.0463   1.846 0.065040 .  
## countyfp85      7.0324     7.0390   0.999 0.317828    
## countyfp87      5.8050     7.0396   0.825 0.409641    
## countyfp89      0.9492     7.1084   0.134 0.893781    
## countyfp91      8.8848     7.0596   1.259 0.208279    
## countyfp93     10.8610     7.0456   1.542 0.123276    
## countyfp95      6.7101     7.0403   0.953 0.340600    
## countyfp97     -2.2777     7.0533  -0.323 0.746768    
## countyfp99     13.8935     7.0402   1.973 0.048519 *  
## countyfp101     2.1063     7.0445   0.299 0.764958    
## countyfp103     3.8916     7.0404   0.553 0.580470    
## countyfp105     6.8541     7.0503   0.972 0.331025    
## countyfp107     2.4290     7.0390   0.345 0.730052    
## countyfp109    11.2195     7.0616   1.589 0.112188    
## countyfp111     3.2019     7.0439   0.455 0.649452    
## countyfp113     5.5167     7.0475   0.783 0.433799    
## countyfp115     8.0182     7.0400   1.139 0.254798    
## countyfp117   -23.7701     7.1360  -3.331 0.000874 ***
## countyfp119     8.4973     7.0446   1.206 0.227815    
## countyfp121    -2.7616     7.0390  -0.392 0.694843    
## countyfp123     8.2674     7.0389   1.175 0.240260    
## countyfp125     2.0919     7.0389   0.297 0.766339    
## countyfp127    13.1465     7.0469   1.866 0.062181 .  
## countyfp129     9.7388     7.1425   1.364 0.172806    
## countyfp131     6.9486     7.0897   0.980 0.327099    
## countyfp133     1.2117     7.0395   0.172 0.863346    
## countyfp135   -16.6425     7.0863  -2.349 0.018900 *  
## countyfp137     6.6056     7.0404   0.938 0.348183    
## countyfp139     8.2715     7.0389   1.175 0.240027    
## countyfp141    13.1679     7.0506   1.868 0.061894 .  
## countyfp143     7.9469     7.0654   1.125 0.260765    
## countyfp145     0.4131     7.0406   0.059 0.953217    
## countyfp147     6.1297     7.0527   0.869 0.384835    
## countyfp149     6.7353     7.0404   0.957 0.338798    
## countyfp151    10.3788     7.0476   1.473 0.140925    
## countyfp153    14.0238     7.0389   1.992 0.046410 *  
## countyfp155    10.4059     7.0864   1.468 0.142075    
## countyfp157    10.1606     7.0397   1.443 0.149014    
## countyfp159   -20.5978     7.0389  -2.926 0.003451 ** 
## countyfp161     8.4110     7.0478   1.193 0.232778    
## countyfp163    15.5360     7.0426   2.206 0.027446 *  
## countyfp165     6.9179     7.0417   0.982 0.325957    
## countyfp167    14.7911     7.0423   2.100 0.035770 *  
## countyfp169    10.2395     7.0458   1.453 0.146233    
## countyfp171     8.7662     7.0459   1.244 0.213519    
## countyfp173   -14.5056     7.0868  -2.047 0.040744 *  
## countyfp175   -12.5580     7.0863  -1.772 0.076452 .  
## countyfp177    -2.8371     7.0524  -0.402 0.687493    
## countyfp179    -3.5740     7.0874  -0.504 0.614105    
## countyfp181    -2.0199     7.0389  -0.287 0.774154    
## countyfp183    10.8835     7.0394   1.546 0.122169    
## countyfp185   -22.9077     7.0863  -3.233 0.001237 ** 
## countyfp187    13.1211     7.0472   1.862 0.062700 .  
## countyfp189     7.5593     7.0757   1.068 0.285441    
## countyfp191     4.0826     7.0867   0.576 0.564584    
## countyfp193     2.3508     7.0395   0.334 0.738436    
## countyfp195     5.9103     7.0954   0.833 0.404908    
## countyfp197    10.4404     7.0518   1.481 0.138817    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 30.68 on 3647 degrees of freedom
## Multiple R-squared:  0.2585, Adjusted R-squared:  0.2382 
## F-statistic: 12.71 on 100 and 3647 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>** Based on the results I’m seeing, I believe that I must be making some kind of mistake, but I’m not sure what that could be. I think there should be a difference in the p-values for the coefficients, but I don’t see any…**</p>
<p>From examining the two different linear regression models, one factoring in countyfp and one not, that including the countyfp as a factor in the regression formula did not affect the significance of the temperature coefficients to any detectable degree. However, including countyfp did slightly alter the values of the coefficients. With the inclusion of countyfp as a factor in the linear regression, meantmax coefficient changed from -3.1665 to -3.1324 while meantmaxsq changed from 168.9590 to 167.9699.</p>
</div>
<div id="plotting-actual-yield-vs.-fitted-yield" class="section level4 hasAnchor" number="7.2.5.2">
<h4><span class="header-section-number">7.2.5.2</span> Plotting Actual Yield vs. Fitted Yield<a href="regressions.html#plotting-actual-yield-vs.-fitted-yield" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="regressions.html#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  Trying to obtain fitted values from the panel regression:</span></span>
<span id="cb119-2"><a href="regressions.html#cb119-2" aria-hidden="true" tabindex="-1"></a>tcy<span class="sc">$</span>p_lm_fit2 <span class="ot">&lt;-</span> panel_lm_W_cfp<span class="sc">$</span>fitted.values</span></code></pre></div>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="regressions.html#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  Plotting yield vs p_lm_fit2</span></span>
<span id="cb120-2"><a href="regressions.html#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tcy) <span class="sc">+</span></span>
<span id="cb120-3"><a href="regressions.html#cb120-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> p_lm_fit2, <span class="at">y =</span> yield))<span class="sc">+</span></span>
<span id="cb120-4"><a href="regressions.html#cb120-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb120-5"><a href="regressions.html#cb120-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Corn Yield vs Panel Regression Fitted Value&quot;</span>,</span>
<span id="cb120-6"><a href="regressions.html#cb120-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;All Iowa Counties, 1981 - 2018&quot;</span>,</span>
<span id="cb120-7"><a href="regressions.html#cb120-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Panel Regression Fitted Value&quot;</span>,</span>
<span id="cb120-8"><a href="regressions.html#cb120-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Actual Corn Yield (bu/acre)&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-71-1.png" width="672" /></p>
</div>
<div id="this-is-the-student-trying-to-leverage-the-panel-regression-funciton-plm-instead" class="section level4 hasAnchor" number="7.2.5.3">
<h4><span class="header-section-number">7.2.5.3</span> This is the Student Trying to Leverage the Panel Regression Funciton plm() Instead<a href="regressions.html#this-is-the-student-trying-to-leverage-the-panel-regression-funciton-plm-instead" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="first-determining-whether-fixed-effects-or-random-effects-model-is-appropriate" class="section level5 hasAnchor" number="7.2.5.3.1">
<h5><span class="header-section-number">7.2.5.3.1</span> <strong>First Determining whether Fixed Effects or Random Effects Model is Appropriate</strong><a href="regressions.html#first-determining-whether-fixed-effects-or-random-effects-model-is-appropriate" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="regressions.html#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First testing the the pooled OLS model:</span></span>
<span id="cb121-2"><a href="regressions.html#cb121-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-3"><a href="regressions.html#cb121-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plmtest</span>(yield <span class="sc">~</span> (meantmaxsq <span class="sc">+</span> meantmax),</span>
<span id="cb121-4"><a href="regressions.html#cb121-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> tcy,</span>
<span id="cb121-5"><a href="regressions.html#cb121-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">effect =</span> <span class="st">&quot;twoways&quot;</span>,</span>
<span id="cb121-6"><a href="regressions.html#cb121-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">&quot;ghm&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Lagrange Multiplier Test - two-ways effects (Gourieroux, Holly and
##  Monfort) for unbalanced panels
## 
## data:  yield ~ (meantmaxsq + meantmax)
## chibarsq = 113671, df0 = 0.00, df1 = 1.00, df2 = 2.00, w0 = 0.25, w1 =
## 0.50, w2 = 0.25, p-value &lt; 2.2e-16
## alternative hypothesis: significant effects</code></pre>
<p>The p-value for this GHM test is very small, and we therefore reject the null hypothesis that there are no significant effects. To be honest, I don’t understand what this test is really testing. I just know that we’re supposed to run prior to running a panel regression, according to Columbia University:
(<a href="https://blogs.cul.columbia.edu/spotlights/2018/11/16/introduction-to-r-plm-package-3/" class="uri">https://blogs.cul.columbia.edu/spotlights/2018/11/16/introduction-to-r-plm-package-3/</a>)</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="regressions.html#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="co">#running the Hausman test to determine whether fixed or random effects model is best</span></span>
<span id="cb123-2"><a href="regressions.html#cb123-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-3"><a href="regressions.html#cb123-3" aria-hidden="true" tabindex="-1"></a><span class="fu">phtest</span>(yield <span class="sc">~</span> (meantmaxsq <span class="sc">+</span> meantmax), </span>
<span id="cb123-4"><a href="regressions.html#cb123-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> tcy,</span>
<span id="cb123-5"><a href="regressions.html#cb123-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">model =</span> <span class="fu">c</span>(<span class="st">&quot;within&quot;</span>,<span class="st">&quot;random&quot;</span>))</span></code></pre></div>
<pre><code>## 
##  Hausman Test
## 
## data:  yield ~ (meantmaxsq + meantmax)
## chisq = 14.986, df = 2, p-value = 0.000557
## alternative hypothesis: one model is inconsistent</code></pre>
<p>The p-value for this Hausman test is small, therefore we conclude that fixed effects model is best.</p>
</div>
</div>
<div id="continuing-wiht-fixed-effects-model" class="section level4 hasAnchor" number="7.2.5.4">
<h4><span class="header-section-number">7.2.5.4</span> Continuing wiht Fixed Effects model<a href="regressions.html#continuing-wiht-fixed-effects-model" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="regressions.html#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Performing fixed effects panel regression</span></span>
<span id="cb125-2"><a href="regressions.html#cb125-2" aria-hidden="true" tabindex="-1"></a>p_tcy <span class="ot">=</span> <span class="fu">pdata.frame</span>(tcy, <span class="at">index =</span> <span class="fu">c</span>(<span class="st">&quot;countyfp&quot;</span>, <span class="st">&quot;year&quot;</span>))</span>
<span id="cb125-3"><a href="regressions.html#cb125-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-4"><a href="regressions.html#cb125-4" aria-hidden="true" tabindex="-1"></a>pan_reg_fe <span class="ot">&lt;-</span> <span class="fu">plm</span>(yield <span class="sc">~</span> (meantmaxsq <span class="sc">+</span> meantmax),</span>
<span id="cb125-5"><a href="regressions.html#cb125-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> p_tcy,</span>
<span id="cb125-6"><a href="regressions.html#cb125-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">model =</span> <span class="st">&quot;within&quot;</span>)</span>
<span id="cb125-7"><a href="regressions.html#cb125-7" aria-hidden="true" tabindex="-1"></a><span class="do">### saving fitted values to p_tcy</span></span>
<span id="cb125-8"><a href="regressions.html#cb125-8" aria-hidden="true" tabindex="-1"></a>p_tcy<span class="sc">$</span>fe <span class="ot">&lt;-</span> pan_reg_fe<span class="sc">$</span>model<span class="sc">$</span>yield</span>
<span id="cb125-9"><a href="regressions.html#cb125-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-10"><a href="regressions.html#cb125-10" aria-hidden="true" tabindex="-1"></a><span class="do">### also getting the residuals</span></span>
<span id="cb125-11"><a href="regressions.html#cb125-11" aria-hidden="true" tabindex="-1"></a>p_tcy<span class="sc">$</span>residuals <span class="ot">&lt;-</span> pan_reg_fe<span class="sc">$</span>residuals </span>
<span id="cb125-12"><a href="regressions.html#cb125-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-13"><a href="regressions.html#cb125-13" aria-hidden="true" tabindex="-1"></a><span class="do">### TRYING FE - RESIDUALS</span></span>
<span id="cb125-14"><a href="regressions.html#cb125-14" aria-hidden="true" tabindex="-1"></a>p_tcy<span class="sc">$</span>fitted <span class="ot">&lt;-</span> p_tcy<span class="sc">$</span>fe <span class="sc">-</span> p_tcy<span class="sc">$</span>residuals</span>
<span id="cb125-15"><a href="regressions.html#cb125-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-16"><a href="regressions.html#cb125-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pan_reg_fe)</span></code></pre></div>
<pre><code>## Oneway (individual) effect Within Model
## 
## Call:
## plm(formula = yield ~ (meantmaxsq + meantmax), data = p_tcy, 
##     model = &quot;within&quot;)
## 
## Unbalanced Panel: n = 99, T = 36-38, N = 3748
## 
## Residuals:
##     Min.  1st Qu.   Median  3rd Qu.     Max. 
## -95.0881 -21.4381  -3.0255  23.5699  77.9414 
## 
## Coefficients:
##             Estimate Std. Error t-value  Pr(&gt;|t|)    
## meantmaxsq  -3.13244    0.17578 -17.820 &lt; 2.2e-16 ***
## meantmax   167.96992    9.89502  16.975 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Total Sum of Squares:    4119000
## Residual Sum of Squares: 3433100
## R-Squared:      0.16652
## Adj. R-Squared: 0.14366
## F-statistic: 364.307 on 2 and 3647 DF, p-value: &lt; 2.22e-16</code></pre>
<p>NOTE: In comparing the coefficient results on the panel regression that used the plm() function (immediately above) to that which used the lm() function (further above), we see that the coefficients of meantmax and meantmaxsq are essentially exactly the same.</p>
</div>
<div id="now-using-the-lm-function-instead" class="section level4 hasAnchor" number="7.2.5.5">
<h4><span class="header-section-number">7.2.5.5</span> Now using the lm() function instead<a href="regressions.html#now-using-the-lm-function-instead" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="regressions.html#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="co">#   TRYING TO FIGURE OUT HOW TO PLOT &quot;actual and fitted yields and interpret the results of your model.&quot; </span></span>
<span id="cb127-2"><a href="regressions.html#cb127-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-3"><a href="regressions.html#cb127-3" aria-hidden="true" tabindex="-1"></a><span class="do">## WHAT IF I DO A REGRESSION ON TOP OF THE plm to get a smooth line?</span></span>
<span id="cb127-4"><a href="regressions.html#cb127-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-5"><a href="regressions.html#cb127-5" aria-hidden="true" tabindex="-1"></a><span class="do">### I think that this is like completing a regression among all of the fitted values.</span></span>
<span id="cb127-6"><a href="regressions.html#cb127-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-7"><a href="regressions.html#cb127-7" aria-hidden="true" tabindex="-1"></a>reg_panreg <span class="ot">&lt;-</span> <span class="fu">lm</span>(fitted <span class="sc">~</span> (meantmaxsq <span class="sc">+</span> meantmax), p_tcy)</span>
<span id="cb127-8"><a href="regressions.html#cb127-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-9"><a href="regressions.html#cb127-9" aria-hidden="true" tabindex="-1"></a>p_tcy<span class="sc">$</span>reg_panreg_fit <span class="ot">&lt;-</span> reg_panreg<span class="sc">$</span>fitted.values</span>
<span id="cb127-10"><a href="regressions.html#cb127-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-11"><a href="regressions.html#cb127-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg_panreg)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = fitted ~ (meantmaxsq + meantmax), data = p_tcy)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -31.401  -2.232   2.084   5.351  15.635 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -2098.6219    39.2415  -53.48   &lt;2e-16 ***
## meantmaxsq     -3.1665     0.0498  -63.59   &lt;2e-16 ***
## meantmax      168.9590     2.7976   60.40   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.88 on 3745 degrees of freedom
## Multiple R-squared:  0.7533, Adjusted R-squared:  0.7531 
## F-statistic:  5717 on 2 and 3745 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Interestingly enough, this regression of the panel regression produces the same coefficient values as the linear regression that did not factor in the countyfp.</p>
<p>This is likely wrong. But if we take the intercept value from the regression that did not include countyfp as a factor, and use the coefficients from the panel regression that did include countyfp as a factor we get the following equation for yield as a function of meantmax:</p>
<p>yield = -3.13244meantmaxsq + 167.96992meantmax -2098.621</p>
<p>It would be interesting to plot this function over the entire data.</p>
</div>
<div id="plotting-above-model-determined-by-panel-regression-over-all-data" class="section level4 hasAnchor" number="7.2.5.6">
<h4><span class="header-section-number">7.2.5.6</span> Plotting Above Model Determined by Panel Regression Over All Data<a href="regressions.html#plotting-above-model-determined-by-panel-regression-over-all-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="regressions.html#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a column on tcy that is this function shown above:</span></span>
<span id="cb129-2"><a href="regressions.html#cb129-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-3"><a href="regressions.html#cb129-3" aria-hidden="true" tabindex="-1"></a>tcy<span class="sc">$</span>experimental_fit <span class="ot">&lt;-</span>  (<span class="sc">-</span><span class="fl">3.13244</span><span class="sc">*</span>tcy<span class="sc">$</span>meantmaxsq) <span class="sc">+</span> (<span class="fl">167.96992</span><span class="sc">*</span>tcy<span class="sc">$</span>meantmax) <span class="sc">-</span> <span class="fl">2098.621</span></span></code></pre></div>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="regressions.html#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the data and the above model:</span></span>
<span id="cb130-2"><a href="regressions.html#cb130-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-3"><a href="regressions.html#cb130-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> tcy)<span class="sc">+</span></span>
<span id="cb130-4"><a href="regressions.html#cb130-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb130-5"><a href="regressions.html#cb130-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> experimental_fit),</span>
<span id="cb130-6"><a href="regressions.html#cb130-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb130-7"><a href="regressions.html#cb130-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="fl">1.25</span>)<span class="sc">+</span></span>
<span id="cb130-8"><a href="regressions.html#cb130-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb130-9"><a href="regressions.html#cb130-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Average Daily Maximum Temperature for Summer Months (°C)&quot;</span>,</span>
<span id="cb130-10"><a href="regressions.html#cb130-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Annual Corn Yield (bu/acre)&quot;</span>,</span>
<span id="cb130-11"><a href="regressions.html#cb130-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Corn Yield vs. Ave. Daily Max. Summer Temp.&quot;</span>,</span>
<span id="cb130-12"><a href="regressions.html#cb130-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;All Iowa Counties, 1981 - 2018&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-77-1.png" width="672" /></p>
</div>
</div>
<div id="question-5-soybeans-download-nass-data-on-soybean-yields-and-explore-either-a-time-series-relationship-for-a-given-county-the-cross-sectional-relationship-for-a-given-year-or-a-panel-across-all-counties-and-years." class="section level3 hasAnchor" number="7.2.6">
<h3><span class="header-section-number">7.2.6</span> Question 5 – Soybeans: Download NASS data on soybean yields and explore either a time series relationship for a given county, the cross-sectional relationship for a given year, or a panel across all counties and years.<a href="regressions.html#question-5-soybeans-download-nass-data-on-soybean-yields-and-explore-either-a-time-series-relationship-for-a-given-county-the-cross-sectional-relationship-for-a-given-year-or-a-panel-across-all-counties-and-years." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="downloading-soybean-data" class="section level4 hasAnchor" number="7.2.6.1">
<h4><span class="header-section-number">7.2.6.1</span> Downloading Soybean Data<a href="regressions.html#downloading-soybean-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="regressions.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="do">## set our API key with NASS</span></span>
<span id="cb131-2"><a href="regressions.html#cb131-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nassqs_auth</span>(<span class="at">key =</span> <span class="st">&quot;6C0A99BB-3CB7-3E99-A699-B9DB7FDB8D16&quot;</span>)</span>
<span id="cb131-3"><a href="regressions.html#cb131-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-4"><a href="regressions.html#cb131-4" aria-hidden="true" tabindex="-1"></a><span class="do">## parameters to query on</span></span>
<span id="cb131-5"><a href="regressions.html#cb131-5" aria-hidden="true" tabindex="-1"></a>params2 <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">commodity_desc =</span> <span class="st">&quot;SOYBEANS&quot;</span>, <span class="at">statisticcat_desc =</span> <span class="st">&quot;PRODUCTION&quot;</span>,</span>
<span id="cb131-6"><a href="regressions.html#cb131-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">prodn_practice_desc =</span> <span class="st">&quot;ALL PRODUCTION PRACTICES&quot;</span>,</span>
<span id="cb131-7"><a href="regressions.html#cb131-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">year__GE =</span> <span class="dv">1981</span>, <span class="at">state_alpha =</span> <span class="st">&quot;IA&quot;</span>)</span>
<span id="cb131-8"><a href="regressions.html#cb131-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-9"><a href="regressions.html#cb131-9" aria-hidden="true" tabindex="-1"></a><span class="co"># download</span></span>
<span id="cb131-10"><a href="regressions.html#cb131-10" aria-hidden="true" tabindex="-1"></a>sbyieldsall <span class="ot">&lt;-</span> <span class="fu">nassqs_yields</span>(params2)</span>
<span id="cb131-11"><a href="regressions.html#cb131-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-12"><a href="regressions.html#cb131-12" aria-hidden="true" tabindex="-1"></a><span class="co">#convert to numeric</span></span>
<span id="cb131-13"><a href="regressions.html#cb131-13" aria-hidden="true" tabindex="-1"></a>sbyieldsall<span class="sc">$</span>county_ansi <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(sbyieldsall<span class="sc">$</span>county_ansi)</span>
<span id="cb131-14"><a href="regressions.html#cb131-14" aria-hidden="true" tabindex="-1"></a>sbyieldsall<span class="sc">$</span>yield <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(sbyieldsall<span class="sc">$</span>Value)</span></code></pre></div>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="regressions.html#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="co">#clean and filter dataset</span></span>
<span id="cb132-2"><a href="regressions.html#cb132-2" aria-hidden="true" tabindex="-1"></a>sbyields <span class="ot">&lt;-</span> <span class="fu">select</span>(sbyieldsall,county_ansi, </span>
<span id="cb132-3"><a href="regressions.html#cb132-3" aria-hidden="true" tabindex="-1"></a>                     county_name, yield, year)<span class="sc">%&gt;%</span></span>
<span id="cb132-4"><a href="regressions.html#cb132-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(county_ansi) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(yield))</span>
<span id="cb132-5"><a href="regressions.html#cb132-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb132-6"><a href="regressions.html#cb132-6" aria-hidden="true" tabindex="-1"></a><span class="co"># make a tibble</span></span>
<span id="cb132-7"><a href="regressions.html#cb132-7" aria-hidden="true" tabindex="-1"></a>sbyields <span class="ot">&lt;-</span> <span class="fu">tibble</span>(cornyields) <span class="sc">%&gt;%</span></span>
<span id="cb132-8"><a href="regressions.html#cb132-8" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(county_name) <span class="sc">%&gt;%</span></span>
<span id="cb132-9"><a href="regressions.html#cb132-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">datapoints =</span> <span class="fu">n</span>())<span class="sc">%&gt;%</span></span>
<span id="cb132-10"><a href="regressions.html#cb132-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="sc">-</span>datapoints)</span></code></pre></div>
</div>
<div id="looking-at-the-trend-of-soybeans-over-time-in-sioux-county" class="section level4 hasAnchor" number="7.2.6.2">
<h4><span class="header-section-number">7.2.6.2</span> Looking at the Trend of Soybeans Over Time in Sioux County<a href="regressions.html#looking-at-the-trend-of-soybeans-over-time-in-sioux-county" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="regressions.html#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sifting out to have only the Winneshiek data</span></span>
<span id="cb133-2"><a href="regressions.html#cb133-2" aria-hidden="true" tabindex="-1"></a>sx_uncln <span class="ot">&lt;-</span> sbyields <span class="sc">%&gt;%</span></span>
<span id="cb133-3"><a href="regressions.html#cb133-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(county_name <span class="sc">==</span> <span class="st">&quot;SIOUX&quot;</span>)</span>
<span id="cb133-4"><a href="regressions.html#cb133-4" aria-hidden="true" tabindex="-1"></a><span class="co">#making sure that there aren&#39;t any rows with NAs:</span></span>
<span id="cb133-5"><a href="regressions.html#cb133-5" aria-hidden="true" tabindex="-1"></a>sx <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(sx_uncln) </span></code></pre></div>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="regressions.html#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting linear regression for time trend:</span></span>
<span id="cb134-2"><a href="regressions.html#cb134-2" aria-hidden="true" tabindex="-1"></a>lm_sx <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> year, <span class="at">data =</span> sx)</span>
<span id="cb134-3"><a href="regressions.html#cb134-3" aria-hidden="true" tabindex="-1"></a>sx<span class="sc">$</span>linear <span class="ot">&lt;-</span> lm_sx<span class="sc">$</span>fitted.values</span>
<span id="cb134-4"><a href="regressions.html#cb134-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb134-5"><a href="regressions.html#cb134-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_sx)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ year, data = sx)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -46.765  -8.374   3.122  12.106  20.091 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -5413.9462   420.0761  -12.89 1.23e-15 ***
## year            2.7852     0.2099   13.27 4.86e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 15.9 on 39 degrees of freedom
## Multiple R-squared:  0.8186, Adjusted R-squared:  0.814 
## F-statistic:   176 on 1 and 39 DF,  p-value: 4.863e-16</code></pre>
<p>According the summary statistics for the linear regression model fitted to the yield ~ year data for Sioux County, there is indeed a quite significant time trend. The slope has a value of 2.7852 yield units increase per year, and the p-value for that slope is 4.86e-16.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="regressions.html#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting yield ~ time along with linear regression:</span></span>
<span id="cb136-2"><a href="regressions.html#cb136-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sx) <span class="sc">+</span></span>
<span id="cb136-3"><a href="regressions.html#cb136-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb136-4"><a href="regressions.html#cb136-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> linear)) <span class="sc">+</span></span>
<span id="cb136-5"><a href="regressions.html#cb136-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb136-6"><a href="regressions.html#cb136-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Annual Soybean Yield (bu/acre)&quot;</span>)<span class="sc">+</span></span>
<span id="cb136-7"><a href="regressions.html#cb136-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Annual Soybean Yield Over Time for Sioux County, Iowa&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-79-1.png" width="672" /></p>
</div>
<div id="examining-whether-rate-of-yield-is-slowing-or-decreasing." class="section level4 hasAnchor" number="7.2.6.3">
<h4><span class="header-section-number">7.2.6.3</span> Examining whether rate of yield is slowing or decreasing.<a href="regressions.html#examining-whether-rate-of-yield-is-slowing-or-decreasing." class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="regressions.html#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Fitting quadratic time trend</span></span>
<span id="cb137-2"><a href="regressions.html#cb137-2" aria-hidden="true" tabindex="-1"></a>sx<span class="sc">$</span>yearsq <span class="ot">&lt;-</span> sx<span class="sc">$</span>year<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb137-3"><a href="regressions.html#cb137-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-4"><a href="regressions.html#cb137-4" aria-hidden="true" tabindex="-1"></a>qd_sx <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> (year <span class="sc">+</span> yearsq), <span class="at">data =</span> sx)</span>
<span id="cb137-5"><a href="regressions.html#cb137-5" aria-hidden="true" tabindex="-1"></a>sx<span class="sc">$</span>quadratic <span class="ot">&lt;-</span> qd_sx<span class="sc">$</span>fitted.values</span>
<span id="cb137-6"><a href="regressions.html#cb137-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-7"><a href="regressions.html#cb137-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(qd_sx)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ (year + yearsq), data = sx)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -46.845  -8.544   3.730  11.856  19.769 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -2.239e+04  8.049e+04  -0.278    0.782
## year         1.975e+01  8.045e+01   0.245    0.807
## yearsq      -4.239e-03  2.010e-02  -0.211    0.834
## 
## Residual standard error: 16.1 on 38 degrees of freedom
## Multiple R-squared:  0.8188, Adjusted R-squared:  0.8093 
## F-statistic: 85.88 on 2 and 38 DF,  p-value: 8.002e-15</code></pre>
<p>We do not find evidence that yield is either slowing or growing with each year.</p>
</div>
</div>
<div id="bonus-1-find-a-package-to-make-a-county-map-of-iowa-displaying-some-sort-of-information-about-yields-or-weather.-interpret-your-map." class="section level3 hasAnchor" number="7.2.7">
<h3><span class="header-section-number">7.2.7</span> Bonus #1: Find a package to make a county map of Iowa displaying some sort of information about yields or weather. Interpret your map.<a href="regressions.html#bonus-1-find-a-package-to-make-a-county-map-of-iowa-displaying-some-sort-of-information-about-yields-or-weather.-interpret-your-map." class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
<div id="bonus-2-challenge-question---map-trends-in-corn-yields-by-county-across-iowa.-interpret-your-map." class="section level3 hasAnchor" number="7.2.8">
<h3><span class="header-section-number">7.2.8</span> Bonus #2: Challenge question - map trends in corn yields by county across Iowa. Interpret your map.<a href="regressions.html#bonus-2-challenge-question---map-trends-in-corn-yields-by-county-across-iowa.-interpret-your-map." class="anchor-section" aria-label="Anchor link to header"></a></h3>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="lake-water-quality-analysis.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/07_regressions_weather_corn.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
